version: '2'
services:
  locative:
    image: locative
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://locative-postgresql:5432/locative'
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  locative-postgresql:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_USER=locative
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
