version: '2'
services:
  locative-app:
    image: locative
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://locative-postgresql:5432/locative
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  locative-postgresql:
    extends:
      file: postgresql.yml
      service: locative-postgresql
